### ISSUE TITLE
be able to detect ip address of the attached device

### ISSUE THREAD

**Issue by vdelendik** [danielpaulus/go-ios#106]
so far detecting of actual device ip is pretty complicated and might be done by WDA logs analysis.
it would be great to identify IPv4 and IPv6 via go ios utility so we can integrate appium etc with no extra steps

**Comment by nanoscopic** [comment]
I've looked extensively for ways to do this directly through usbmuxd/lockdown.

It cannot be done directly. The closest you can get is fetching the MAC address of the wifi/ethernet interface via gestalt. Once you have that it an be used to determine the IP address. A scan may need to be done of the network though to populate the ARP table to be able to do it.

Alternatively, launch WDA or CFA and make a call there and you can fetch this information.

It is not complicated to fetch it within Xctest code. It is just a standard call to getifaddrs.

**Comment by danielpaulus** [comment]
@vdelendik  yesterday I got the idea to try and use the pcap dump the iphone gives us to figure out the ip address. 
Check this out: [figureout_ip](https://github.com/danielpaulus/go-ios/pull/110)
for it to work, you have to disable the private wifi address feature first, otherwise the wifi MAC will be different all the time and I did not find a way to retrieve the private MAC.

Then you just have to wait until the iphone sends anything to the internet using ipv4 to get the address.
I thought about an option to open apple maps f.ex. to make this faster.

**Comment by danielpaulus** [comment]
Try it out and let me know if it works :-) 
Be sure to read the manual.
