### ISSUE TITLE
Any plan for implementation of com.apple.os_trace_relay

### ISSUE THREAD

**Issue by Dantee296** [danielpaulus/go-ios#216]
@danielpaulus 

do u have any roadmaps / plan for implementing this service in go-ios

```
as com.apple.syslog_relay Just streams syslog lines as raw strings
For a more robust structural parsing,  com.apple.os_trace_relay service is better
```

pymobiledevice3 already implemented it
`https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/services/os_trace.py`

**Comment by Dantee296** [comment]
@danielpaulus

**Comment by nanoscopic** [comment]
It is pretty easy to implement. Do you know how to code in Golang? The best path for cooperation would be to implement this yourself for all of us and to submit it as a PR to the project.

Daniel generously provides this provide free for all of us to use and created it in his free time. Perhaps assist instead of asking for an update?

If you are unable, someone perhaps will do this eventually. Thank you for submitting the ticket with the link.

What definitely won't make it happen any faster is asking for updates. Please don't.

**Comment by Dantee296** [comment]
@nanoscopic  what i dont understand is when ever i tag @danielpaulus for something , you always drop in with long harsh wordings, you did that on my other issue as well 

you started doing here too 
i really dont understand your problem 🙂

is this github bug ? tagging him makes you appear on issues

i didnt ask you for update
and there is no issues asking about something , this is why github "issues"section exist.
