### ISSUE TITLE
Is there a way to get device screen-size?

### ISSUE THREAD

**Issue by inluxc** [danielpaulus/go-ios#46]
Is there a way to get device screen-size?

**Comment by danielpaulus** [comment]
Ways I can think of from the top of my head:
1. take a screenshot and grab the dimensions
2. grab a static list from somewhere on the internet and use the device model
3.  write a simple app that resolves it using code (f.ex. like here: https://medium.com/@marksiu/how-to-detect-ios-device-models-and-screen-size-8de1e55d2425) and launch the app with go-ios

**Comment by nanoscopic** [comment]
On some devices the screen dimensions are available within mobilegestalt data. It is only some though, so it is not a reliable method.

Be aware that there is also a difference between screen physical size in pixels and addressable resolution. Depending on the device and settings the ratio between physical pixels and resolution from app perspective is different.

This is why the method of reading it from an app is one of the best solutions.

The solution of using a device to size map does not actually work, because iOS lets you choose between two different ratios. Depending on what the user has chosen the app resolution will be different.

A screenshot from the device also may not match the resolution from the app perspective.

Sadly lockdown does not provide an RPC function call to fetch the current screen size from an app perspective. ( that I have yet been able to locate at least )

**Comment by danielpaulus** [comment]
closing as I moved htis to Q&A here: https://github.com/danielpaulus/go-ios/discussions/89
