### ISSUE TITLE
1.Is it possible to install web_Driver agent with go-ios (without xcode)?

### ISSUE THREAD

**Issue by Kristiyan-R-Dimitrov** [danielpaulus/go-ios#72]
1.Is it possible to install web_Driver agent with go-ios (without xcode)?
2.Is there a way to have preinstalled web driver agent on the device(without mac and xcode)?
3.I'm trying to follow the steps but when I try to build the docker but when i come to this step ./run.sh ios-appium-on-linux I'm getting this 
{"level":"info","msg":"Start listening on port 7777 forwarding to port 8100 on device","time":"2021-11-09T11:47:17Z"}
/startAppium.sh: line 11: /root/.nvm/versions/node/v14.16.0/bin/appium: No such file or directory

Thank you in advance!

**Comment by nanoscopic** [comment]
Yes. WDA can be installed with any program able to install apps to an iOS device, including with go-ios.

You just install the built WebDriverAgentRunner.

You still need to sign the Runner though just as any normal iOS app. If you don't want to use Xcode to do the signing you can use a resigning tool of some sort.

As for help using Appium scripts you'll need to talk to Appium maintainers.

WDA can be run using go-ios once it is installed.

If you are going to refer to steps "run.sh ios-appium-on-linux" please at least link to the steps you are referring to otherwise no one will have any idea what you are talking about exactly.

**Comment by Kristiyan-R-Dimitrov** [comment]
Sorry about that, I'm following the steps from here https://github.com/danielpaulus/ios-appium-on-linux

Run appium for iOS devices on Linux

1.Install WebDriverAgent on your iOS device using Xcode, then plug the device into your Linux box
2.Install usbmuxd on your linux box apt install usbmuxd and run it sudo usbmuxd&
3.Clone this repo on the Linux box
4.Run: docker build -t ios-appium-on-linux .
5.Run: ./run.sh ios-appium-on-linux to start the container
6.Run: docker exec CONTAINER_ID /ios runwda to start WebDriverAgent
7.Now you can run any appium script on the linux box, f.ex. try node client/test.js to try the script included in this repo.

**Comment by shamanec** [comment]
Hey, Kristiyan, you can check out my updated https://github.com/shamanec/ios-appium-docker project that uses 'go-ios' to spin up an iOS Appium container on Linux. Note that as David mentioned you still need to sign the WDA using Xcode(or other resigning tool) because you probably will not be able to use the one included in the project files. If you have no access to a Mac machine I could probably provide you with an updated signed WDA (after you give me a device UDID) that you could use to check it out. Go go 'go-ios'!

**Comment by shamanec** [comment]
You can do this without using docker by adapting the following commands:
" ./ios install --path=WebDriverAgent.ipa --udid=$DEVICE_UDID"
where the path value is the signed file you have prepared and UDID is the udid of the device on which you want to install it.
Then run the WDA on the device with:
"./ios runwda --bundleid=$WDA_BUNDLEID --testrunnerbundleid=$WDA_BUNDLEID --xctestconfig=WebDriverAgentRunner.xctest --env USE_PORT=10000 --udid $DEVICE_UDID"
where WDA_BUNDLEID is the bundleID you provided before signing and building WDA as explained here: http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ . After that you should be able to connect with Appium by providing the "webDriverAgentUrl":"'http:$deviceIP:10000'" capability on por

**Comment by danielpaulus** [comment]
One thing I thought about was setting up a github actions pipeline to automatically build and sign WDA. Github Actions has full MacOS support. So you could run all of it without the need of a Mac. Let me know if this is interesting for you, then I will update my stuff accordingly.

**Comment by Kristiyan-R-Dimitrov** [comment]
> One thing I thought about was setting up a github actions pipeline to automatically build and sign WDA. Github Actions has full MacOS support. So you could run all of it without the need of a Mac. Let me know if this is interesting for you, then I will update my stuff accordingly.

Sorry for the late answer, that will be great!
Thank you!

**Comment by danielpaulus** [comment]
I am slowly getting there. I have built this tool: https://github.com/danielpaulus/app-signer
that will resign any app with a given p12 and mobileprovisioning profile for a udid. 
I merged a xcuirunner_test today that uses it. Not super well documented yet, but maybe you can already take a look.

**Comment by danielpaulus** [comment]
Check out this workflow example https://github.com/danielpaulus/go-ios/blob/01a453724a3c495adb284620ca00a58a4314320f/.github/workflows/real-device.yml#L17
it shows how to sign wda for your device on a github action mac. 
All you need is to add p12 and mobileprovisioning file as a repo secret in base64 coding. 

I will also write a medium article with the details, probably this week about it.

**Comment by danielpaulus** [comment]
I added https://github.com/danielpaulus/wda-signer for this purpose. You can use it to sign the latest wda with a p12 and mobileprovision file for any of your devices. That removes the need for owning a mac.
